version: "3.9"
services:
  mysql:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql@123
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
    container_name: mysql-container

  spring-boot:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - springboot-mysql-net
    container_name: chaos

networks:
  springboot-mysql-net:
