# Use a base image of MySQL
FROM mysql:latest

# Set the root password for MySQL
ENV MYSQL_ROOT_PASSWORD=Mysql@123

# Create the login_system database
ENV MYSQL_DATABASE=login_system1

# Set the character set and collation for the database
ENV MYSQL_CHARSET=utf8mb4
ENV MYSQL_COLLATION=utf8mb4_general_ci

# Expose the default MySQL port
EXPOSE 3306

